paths: 
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200": 
          description: Obtiene todos los productos
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del server
    post:
      summary: Este endpoint crea un producto
      tags:
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: El producto fue creado con exito
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por id
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del Producto llamado pid, que desea solicitar
          schema: 
            type: string
      responses:
        "200":
          description: El producto fue obtenido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
    put:
      summary: Actualiza un producto por id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del Producto llamado pid, que desea actualizar
          schema: 
            type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: El producto fue actualizado con éxito
        "404":
          description: Producto no encontrado  
    delete:
      summary: Elimina un producto por id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del Producto llamado pid, que desea eliminar
          schema: 
            type: string
      responses:
        "204":
          description: El producto fue eliminado correctamente
        "404":
          description: Producto no encontrado
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado por mongo 
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        thumbnail:
          type: string
          description: imagen
        category:
          type: string
          description: tipo de categoria
      example:
        _id: "65ab0bf9ae9d14885911b353"
        title: Botines
        description: botines con tacon
        price: 2050
        thumbnail: "https://inside-sho.com/354799/botines-con-tacon-y-hebilla.webp"
        category: botas
  
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        thumbnail:
          type: string
          description: imagen
        category:
          type: string
          description: tipo de categoria
      example:
        title: Botines
        description: botines con tacon
        price: 2050
        thumbnail: "https://inside-sho.com/354799/botines-con-tacon-y-hebilla.webp"
        category: botas
  